#@ load("@ytt:data", "data")
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: #@ data.values.app_name
  labels:
    app: #@ data.values.app_name
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels:
      app: #@ data.values.app_name
  template:
    metadata:
      labels:
        app: #@ data.values.app_name
    spec:
      containers:
      - name: echo-server
        image: jmalloc/echo-server
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
