#@ load("@ytt:data", "data")
---
kind: Service
apiVersion: v1
metadata:
  name: #@ data.values.app_name
spec:
  selector:
    app: #@ data.values.app_name
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
