name: continuous integration
on:
  - push
  - pull_request

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kustomize-version:
          - "4.0.5"
          - "4.1.3"
        ytt-version:
          - "v0.33.0"
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: install python deps
        run: |
          pip install pyyaml
      - name: install kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: ${{ matrix.kustomize-version }}
      - name: install ytt 0.33.0
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: ytt
          ytt: ${{ matrix.ytt-version }}
      - name: run tests
        # TODO: Better test machinery.
        # We run each example and overwrite the expected output with the actual
        # output, relying on git diff to tell us about any divergence.
        run: |
          export KUSTOMIZE_PLUGIN_HOME=$(pwd)/kustomize/plugin
          for example in example/*; do
            (cd example/basic/; kustomize build --enable-alpha-plugins > expected-output.yaml)
          done
          git status
          git diff --exit-code
